version: "3.9"

services:
  telegram-bot-server:
    # containerized version of https://github.com/tdlib/telegram-bot-api
    image: "ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:latest"
    command: --local --dir="/data"
    volumes:
    - telegram-bot-server:/data
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
  telegram-bot-server:
