# Generated by Django 3.2 on 2021-04-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_telegrambotmodel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
